### ISSUE TITLE
Running in cpu

### ISSUE THREAD

**Issue by Zumbalamambo** [kenshohara/video-classification-3d-cnn-pytorch#1]
Im getting the following error while running in cpu

`AssertionError: Torch not compiled with CUDA enabled
`

**Comment by kenshohara** [comment]
Because the pretrained model needs gpu, the error ocurred.
I will upload cpu ver. of the pretrained model.
Please wait until the uploading.

**Comment by kenshohara** [comment]
I uploaded the cpu version (resnet-34-kinetics-cpu.pth) [here](https://github.com/kenshohara/3D-ResNets-PyTorch/releases/tag/1.0).
Please use this model.
If the issue is not solved by the cpu version, ask me again.
