### ISSUE TITLE
Layer by layer features

### ISSUE THREAD

**Issue by gkv91** [kenshohara/video-classification-3d-cnn-pytorch#11]
Hi,
How can I use the pre-trained (.pth) files in my pytorch code?. I need to extract the layer by layer features of the video. 
Thnaks

**Comment by kenshohara** [comment]
This is the line related to load the pretrained parameters.
https://github.com/kenshohara/video-classification-3d-cnn-pytorch/blob/master/main.py#L26

You should reimplement my model, and output the features of each layer by changing ```forward()```.
