### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by LakyTT** [kenshohara/video-classification-3d-cnn-pytorch#12]
Hi ,thanks for your this work.
Now I meet this question:
when I excute:python3 main.py --input ./input --video_root ./videos --output ./output.json --model ./resnext-101-64f-kinetics.pth --mode score
videos include my vides.
I get this problem:loading model ./resnext-101-64f-kinetics.pth
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    assert opt.arch == model_data['arch']
AssertionError
I don't know why?
thank you

**Comment by LakyTT** [comment]
And when I excute :python3 main.py --input ./input --video_root ./videos --output ./output.json --model ./resnext-34-kinetics.pth --mode score
I get:raceback (most recent call last):
  File "main.py", line 24, in <module>
    model_data = torch.load(opt.model)
  File "/home/user/.conda/envs/jck_caffe/lib/python3.6/site-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "/home/user/.conda/envs/jck_caffe/lib/python3.6/site-packages/torch/serialization.py", line 427, in _load
    deserialized_objects[key]._set_from_file(f, offset)
RuntimeError: storage has wrong size: expected 33567042 got 512

I don't know how to solve it

**Comment by kenshohara** [comment]
You should execute the followings.

```
python3 main.py --input ./input --video_root ./videos --output ./output.json --model ./resnext-101-64f-kinetics.pth --mode score --model_name resnext --model_depth 101
```
In addition, you have to change sample_duration by modifying [this line](https://github.com/kenshohara/video-classification-3d-cnn-pytorch/blob/master/main.py#L19).

**Comment by LakyTT** [comment]
Thank you so much！I  solved it several days ago through the code .
Still thanks！！and you did a very good job.
Best  wishes
