### ISSUE TITLE
fc7-1 features

### ISSUE THREAD

**Issue by ksharsha** [kenshohara/video-classification-3d-cnn-pytorch#2]
I wanted to know how I could extract the fc7 layer features which is of 4096 dimensions instead of the global average pooled features. Thanks!

**Comment by kenshohara** [comment]
ResNet does not include fc7 layer.
ResNet consists of conv1, conv2, conv3, conv4, conv5, global average pooling, and fc.
Do you mean conv5, which locate before global average pooling?

**Comment by ksharsha** [comment]
Got it thanks, mistook the model for a VGG based C3D model.

**Comment by ksharsha** [comment]
I want to train C3D on another dataset and I was wondering how long it would take to train the C3D model?

**Comment by kenshohara** [comment]
It depends on your machine power and size of the dataset.
FYI, ResNet-18 training on Kinetics using 4 TITAN X was finished for 1 week.

**Comment by ksharsha** [comment]
Thanks!
