### ISSUE TITLE
structure of data directory for "--mode feature"

### ISSUE THREAD

**Issue by hjeun** [kenshohara/video-classification-3d-cnn-pytorch#23]
Im trying to extract feature of my own videos.
How to set the structure of data directory?
I got error comment "video1.mp4 does not exist" "video2.mp4 does not exist".
I used the command below.
There are subfolders named as classes under UCF-101 just like the original structure of data directory.

python3 main.py --input ./input --video_root ../dataset/UCF-101 --output ./output.json --model_name resnext --model_depth 101 --model ./data/results/resnext-101-kinetics.pth --mode feature --resnet_shortcut B

**Comment by Mohamad73** [comment]
Hello, how did u solve the problem, I am getting the same error.

**Comment by snjiang77** [comment]
Have you solved this problem already?Can you tell me how you did it?

**Comment by vhvkhoa** [comment]
You should look at the content of ./input file.
input contains (relative or absolute) paths to videos you want to extract features from.
