### ISSUE TITLE
Final ACCURACY

### ISSUE THREAD

**Issue by Mohamad73** [kenshohara/video-classification-3d-cnn-pytorch#32]
Thank you for your great work!
I understand that there is eval_ucf101.py to get the overall accuracy. I am not sure how to use it though. I read that i can use it like the activity net classification and also I have been reading that there is ucf101_01.json which I think it the groundtruth of ucf101 but also I dont know where I get it from.
I would appreciate anybody's help.

**Comment by Mohamad73** [comment]
Closing this issue as I had to use this command line. 
python utils/ucf101_json.py annotation_dir_path

**Comment by fnj1017** [comment]
What is "pandas" in the import line? I get error of "pandas" module not found.
