### ISSUE TITLE
Could you restore the pre-trained model?

### ISSUE THREAD

**Issue by jiangqy** [kenshohara/video-classification-3d-cnn-pytorch#34]
@kenshohara Hi, thanks for your sharing. 

I want to download the pre-trained model. However it was put into recycle bin. Could you please restore the file?

thanks.

**Comment by ashar-ali** [comment]
Has the pre-trained model moved to a new location? I am unable to access the google drive link provided with the repository.

**Comment by bayesianio** [comment]
Same here. Where is the pre-trained model?

**Comment by kenshohara** [comment]
I'm sorry. I fixed the link.
