### ISSUE TITLE
some problem on Temporal duration

### ISSUE THREAD

**Issue by CCV-Edward** [kenshohara/video-classification-3d-cnn-pytorch#5]
Thanks for your fantastic work!
I want to extract fixed length 3d feature of different video, what parameter should i set ?
For example, a video have 300 frames, and i want to get 16 3d features, and sample_duration would be set as 18; while if the length of video is 400, the sample_duration would be set as 25. How can i get adaptive sample_duration ？

**Comment by kenshohara** [comment]
If you want to use my pretrained models, you should use 16 frame sample_duration,
because different sample_duration requires training again.
So, changing the number of extracted features is easy compared with changing sample_duration.

**Comment by CCV-Edward** [comment]
Thanks for your answer!
As you mentioned, all the models are trained on Kinetics, it will be useful for the task on UCF101?

**Comment by CCV-Edward** [comment]
Could you please present the model trained on UCF101 and HMDB51?
I want to verify my model with the features extracted from your work
Thank you very much!

**Comment by kenshohara** [comment]
Which model do you want to use?
I don't have sufficient storage to upload all of the models.
So if you tell me, I can upload the part of the models.

**Comment by CCV-Edward** [comment]
I want to use the model which extracts 3d-features of UCF101 and HMDB51.

Regards.

**Comment by kenshohara** [comment]
I mean, for example, resnet-18, 34, or resnext-101.
Currently uploaded pretrained models are trained on only Kinetics,
but I have models pretrained on Kinetics and finetuned on UCF-101 or HMDB-51.
So, I can upload UCF-101 and HMDB-51 finetuned models.
But uploading all models (i.e. resnet-18, 34, 50, ... 20, resnext-101, ...) is difficult.

**Comment by CCV-Edward** [comment]
Sorry!
Could you please upload resnext-101 models finetuned on UCF-101 and HMDB-51

**Comment by CCV-Edward** [comment]
In your paper, you said ResNeXt-101 (64f) is the best model. I want to get some comparison with model, thank  you!

**Comment by kenshohara** [comment]
I uploaded the models at the same link as the other models.
```resnext-101-kinetics-ucf101_split1.pth``` is the ucf-101 finetuned resnext-101.
```resnext-101-64f-kinetics-ucf101_split1.pth``` is the ucf-101 finetuned rexnext-101 (64f).

**Comment by CCV-Edward** [comment]
Thank you!!!
