### ISSUE TITLE
The normalization of the input image ? 

### ISSUE THREAD

**Issue by Fly2flies** [kenshohara/video-classification-3d-cnn-pytorch#63]
Thanks for sharing the great code base. 
But I still have a little puzzle:
in the [get_mean()](https://github.com/kenshohara/video-classification-3d-cnn-pytorch/blob/master/mean.py#2), the mean is _[114.7748, 107.7354, 99.4750]_.  It looks like this is for images with input ranges from 0 to 255. But in the normalization for [input image](https://github.com/kenshohara/video-classification-3d-cnn-pytorch/blob/master/classify.py#14)
```
spatial_transform = Compose([Scale(opt.sample_size),
                                 CenterCrop(opt.sample_size),
                                 ToTensor(),
                                 Normalize(opt.mean, [1, 1, 1])])
```

after `ToTensor()`, the value becomes [0,1]. 
Is this appropriate for subsequent video classifications? Do we need to swap the order of these two operations ?

**Comment by R00Kie-Liu** [comment]
Different from the official implementation of ToTensor() in PyTorch, this Totensor() class doesn't normalize the values to [0,1] . It just converts PIL data to torch tensor format.

**Comment by Fly2flies** [comment]
> Different from the official implementation of ToTensor() in PyTorch, this Totensor() class doesn't normalize the values to [0,1] . It just converts PIL data to torch tensor format.

Ok, I got it. Thanks for your reply.
